# Generated by Django 3.1.7 on 2021-03-13 05:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customuser_token_confirmation_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='token_confirmation_email',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
    ]
