# Generated by Django 3.1.7 on 2021-03-20 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20210313_0530'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='code_recover_password',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
