# Generated by Django 3.1.4 on 2020-12-13 22:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shareroutinepublic',
            name='url',
        ),
        migrations.AlterField(
            model_name='shareroutinepublic',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
