# Generated by Django 3.1.3 on 2020-11-17 00:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_public', models.BooleanField(default=False)),
                ('time', models.IntegerField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('dificulty', models.CharField(choices=[('novice', 'Novice'), ('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('legendary', 'Legendary')], max_length=15)),
                ('muscle_group', models.CharField(choices=[('fullbody', 'Full Body'), ('chest', 'Chest'), ('legs', 'Legs'), ('arm', 'Arm'), ('back', 'Back'), ('shoulder', 'Shoulder')], max_length=10)),
                ('cover', models.ImageField(upload_to='routine-images')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routines_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
