# Generated by Django 3.1.3 on 2020-11-27 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routines', '0002_executionblock_executionexercise'),
    ]

    operations = [
        migrations.AddField(
            model_name='executionblock',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
