# Generated by Django 3.1.3 on 2020-12-03 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routines', '0003_executionblock_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routine',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='routine-images'),
        ),
    ]
