name: Docker compose dev CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest
    env:
      DEBUG: 1
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      DJANGO_ALLOWED_HOSTS: localhost 127.0.0.1 [::1]
      SQL_ENGINE: django.db.backends.postgresql
      SQL_DATABASE: ${{ secrets.SQL_DATABASE }}
      SQL_USER: ${{ secrets.SQL_USER }}
      SQL_PASSWORD: ${{ secrets.SQL_PASSWORD }}
      SQL_HOST: db
      SQL_PORT: 5432
      DATABASE: postgres

    steps:
    - uses: actions/checkout@v2
    - name: Build the docker-compose
      run: docker-compose up -d
    - name: Check containers running
      run: docker ps -a
    - name: Run test suit
      run: docker-compose exec web python manage.py test

